//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megumirai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int ItemId { get; set; }
        public string ItemName { get; set; }
        public string ItemPhoto { get; set; }
        public string Category { get; set; }
        public int UnitPrice { get; set; }
        public string Size { get; set; }
        public string Assortment { get; set; }
        public int Stock { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
    }
}
