//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megumirai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public decimal OrderId { get; set; }
        public decimal OrderDetailId { get; set; }
        public decimal ItemId { get; set; }
        public int Quantity { get; set; }
        public int Price { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public string Status { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Order Order { get; set; }
    }
}
