//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megumirai.Models
{
    using System;
    using System.Collections.Generic;

    public partial class OrderMix
    {
        public int OrderMixId { get; set; }
        public int OrderId { get; set; }
        public int OrderDetailId { get; set; }
        public int ItemId { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> UnitPrice { get; set; }
        public int Quantity { get; set; }
        public int Price { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public string Status { get; set; }
        public int CustomerId { get; set; }
        public int SubPrice { get; set; }
        public int Tax { get; set; }
        public int TotalPrice { get; set; }
        public System.DateTime OrderDate { get; set; }

        public virtual Customer Customer { get; set; }
        public virtual Order Order { get; set; }

        public override string ToString()
        {
            return string.Format("OrderMix[OrderMixId={0}, " +
                 "OrderId={1}, " + "OrderDetailId={2}, " + "ItemId={3}", "ItemName={4}",
                 "UnitPrice={5}," + "Quantity={6}," + "Price={7}," + "DeliveryDate={8}," + "Status={9},"
                 + "CustomerId={10}," + "SubPrice={11}," + "Tax={12}," + "TotalPrice={13}," + "OrderDate={14}]",
                 OrderMixId,OrderId,  OrderDetailId, ItemId, ItemName, UnitPrice,
                 Quantity, Price, Status, CustomerId, Tax, TotalPrice, OrderDate);
        }
               

     
        }
    }


